services:
  jenkins:
    hostname: jenkins
    container_name: jenkins
    image: bohkuba/alpine-jenkins
    restart: on-failure
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

  worker:
    hostname: worker
    container_name: worker
    image: bohkuba/alpine-worker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
